version: '3.8'

services:
  weather-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.weathermcpserver
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
